spring:
  r2dbc:
    url: &dbURL r2dbc:mysql://localhost:3306/funesto
    username: &dbUser root
    password: &dbPassword 123456
  flyway:
    url: jdbc:mysql://localhost:3306/funesto
    user: root
    password: 123456
    baseline-on-migrate: true

